/**
 * Realistic Dummy Data Presets for all form types in Marketing-OS.
 * Each category contains exactly 10 high-quality, localized realistic presets.
 */

export const DUMMY_PRESETS = {
  campaigns: [
    {
      id: 1,
      title: 'Summer Mega Discount 2026',
      subtitle: '₹1,50,000 Budget • WhatsApp & Instagram',
      data: {
        campaign_name: 'Summer Mega Discount 2026',
        campaign_type: 'discount',
        start_date: '2026-06-01',
        end_date: '2026-06-30',
        budget: 150000,
        status: 'active',
        channels: ['WhatsApp', 'Instagram'],
        target_audience: 'Retail & B2B Shoppers',
      },
    },
    {
      id: 2,
      title: 'Diwali Appliance Launch',
      subtitle: '₹3,00,000 Budget • Google Ads & Facebook',
      data: {
        campaign_name: 'Diwali Premium Appliance Launch',
        campaign_type: 'product',
        start_date: '2026-10-15',
        end_date: '2026-11-15',
        budget: 300000,
        status: 'planned',
        channels: ['Google Ads', 'Facebook'],
        target_audience: 'Homeowners & High Net Worth Clients',
      },
    },
    {
      id: 3,
      title: 'B2B Corporate Outreach Q3',
      subtitle: '₹85,00,0 Budget • LinkedIn & Email',
      data: {
        campaign_name: 'B2B Enterprise Solutions Drive',
        campaign_type: 'branding',
        start_date: '2026-07-01',
        end_date: '2026-09-30',
        budget: 85000,
        status: 'active',
        channels: ['LinkedIn', 'Google Ads'],
        target_audience: 'IT Procurement Managers & CTOs',
      },
    },
    {
      id: 4,
      title: 'Monsoon Clearance Blitz',
      subtitle: '₹45,000 Budget • WhatsApp & Facebook',
      data: {
        campaign_name: 'Monsoon Super Clearance Sale',
        campaign_type: 'discount',
        start_date: '2026-07-15',
        end_date: '2026-08-10',
        budget: 45000,
        status: 'active',
        channels: ['WhatsApp', 'Facebook'],
        target_audience: 'Existing Subscribers & Bargain Buyers',
      },
    },
    {
      id: 5,
      title: 'New Flagship Store Grand Opening',
      subtitle: '₹1,20,000 Budget • Instagram & Google Ads',
      data: {
        campaign_name: 'Connaught Place Store Grand Opening',
        campaign_type: 'branding',
        start_date: '2026-08-01',
        end_date: '2026-08-20',
        budget: 120000,
        status: 'planned',
        channels: ['Instagram', 'Google Ads'],
        target_audience: 'Delhi NCR Shoppers',
      },
    },
    {
      id: 6,
      title: 'Independence Day Freedom Deal',
      subtitle: '₹75,000 Budget • WhatsApp & LinkedIn',
      data: {
        campaign_name: 'Freedom Fest 15th August Sale',
        campaign_type: 'festival',
        start_date: '2026-08-10',
        end_date: '2026-08-18',
        budget: 75000,
        status: 'planned',
        channels: ['WhatsApp', 'LinkedIn'],
        target_audience: 'Pan-India Corporate Accounts',
      },
    },
    {
      id: 7,
      title: 'VIP Client AMC Renewal Drive',
      subtitle: '₹30,000 Budget • WhatsApp Direct',
      data: {
        campaign_name: 'Q3 Annual Maintenance Renewal Drive',
        campaign_type: 'branding',
        start_date: '2026-09-01',
        end_date: '2026-09-25',
        budget: 30000,
        status: 'planned',
        channels: ['WhatsApp'],
        target_audience: 'Existing Commercial Clients',
      },
    },
    {
      id: 8,
      title: 'Eco Organic Product Launch',
      subtitle: '₹2,00,000 Budget • Instagram & Facebook',
      data: {
        campaign_name: 'EcoSmart Green Line Launch',
        campaign_type: 'product',
        start_date: '2026-09-10',
        end_date: '2026-10-10',
        budget: 200000,
        status: 'planned',
        channels: ['Instagram', 'Facebook'],
        target_audience: 'Environmentally Conscious Buyers',
      },
    },
    {
      id: 9,
      title: 'Year-End Inventory Liquidation',
      subtitle: '₹90,000 Budget • Facebook & Instagram',
      data: {
        campaign_name: 'Year End Stock Clearance 2026',
        campaign_type: 'discount',
        start_date: '2026-12-15',
        end_date: '2026-12-31',
        budget: 90000,
        status: 'planned',
        channels: ['Facebook', 'Instagram'],
        target_audience: 'Price sensitive retail customers',
      },
    },
    {
      id: 10,
      title: 'Mobile App Sign-up Cashback',
      subtitle: '₹1,80,000 Budget • Google Ads & Instagram',
      data: {
        campaign_name: 'Pucho App Download Cash Reward',
        campaign_type: 'product',
        start_date: '2026-07-01',
        end_date: '2026-08-31',
        budget: 180000,
        status: 'active',
        channels: ['Google Ads', 'Instagram'],
        target_audience: 'Tech Savvy Mobile Users',
      },
    },
  ],

  leads: [
    {
      id: 1,
      title: 'Rajesh Sharma - Retail Inquiry',
      subtitle: 'Delhi • WhatsApp • Revenue: ₹45,000',
      data: {
        name: 'Rajesh Sharma',
        email: 'rajesh.sharma@gmail.com',
        phone: '9876543210',
        source: 'WhatsApp',
        campaign_id: 'CMP001',
        status: 'new',
        created_date: '2026-06-01',
        revenue: 45000,
        notes: 'Inquired for bulk purchase of 50 AC units for store.',
      },
    },
    {
      id: 2,
      title: 'Priya Patel - B2B Bulk Buyer',
      subtitle: 'Mumbai • Google Ads • Revenue: ₹1,80,000',
      data: {
        name: 'Priya Patel (Patel Enterprises)',
        email: 'priya@patelenterprises.com',
        phone: '9820011223',
        source: 'Google Ads',
        campaign_id: 'CMP002',
        status: 'qualified',
        created_date: '2026-06-03',
        revenue: 180000,
        notes: 'Needs custom quotation for commercial HVAC system.',
      },
    },
    {
      id: 3,
      title: 'Vikram Malhotra - Franchise Inquiry',
      subtitle: 'Bangalore • Instagram • Revenue: ₹3,50,000',
      data: {
        name: 'Vikram Malhotra',
        email: 'vikram.m@malhotragroup.in',
        phone: '9900112233',
        source: 'Instagram',
        campaign_id: 'CMP003',
        status: 'contacted',
        created_date: '2026-06-05',
        revenue: 350000,
        notes: 'Looking to set up regional distribution hub in South India.',
      },
    },
    {
      id: 4,
      title: 'Ananya Gupta - Corporate Supply Lead',
      subtitle: 'Hyderabad • LinkedIn • Revenue: ₹2,20,000',
      data: {
        name: 'Ananya Gupta (TechCorp Ltd)',
        email: 'ananya.g@techcorp.com',
        phone: '9701122334',
        source: 'Facebook',
        campaign_id: 'CMP004',
        status: 'converted',
        created_date: '2026-06-07',
        converted_date: '2026-06-15',
        revenue: 220000,
        notes: 'Annual vendor contract approved and signed.',
      },
    },
    {
      id: 5,
      title: 'Suresh Kumar & Sons - Wholesale Trader',
      subtitle: 'Ahmedabad • Facebook • Revenue: ₹5,00,000',
      data: {
        name: 'Suresh Kumar Traders',
        email: 'suresh@sktraders.co.in',
        phone: '9898012345',
        source: 'Facebook',
        campaign_id: 'CMP005',
        status: 'qualified',
        created_date: '2026-06-09',
        revenue: 500000,
        notes: 'Requesting 20% trade discount for initial order.',
      },
    },
    {
      id: 6,
      title: 'Meera Reddy - Interior Designer',
      subtitle: 'Chennai • Instagram • Revenue: ₹1,25,000',
      data: {
        name: 'Meera Reddy Design Studio',
        email: 'meera@reddydesigns.com',
        phone: '9444055667',
        source: 'Instagram',
        campaign_id: 'CMP006',
        status: 'new',
        created_date: '2026-06-10',
        revenue: 125000,
        notes: 'Interested in luxury lighting and appliance catalog.',
      },
    },
    {
      id: 7,
      title: 'Sunita Verma - Hotel Chain Buyer',
      subtitle: 'Jaipur • WhatsApp • Revenue: ₹95,000',
      data: {
        name: 'Sunita Verma (Palace Hotels)',
        email: 'purchase@palacehotels.in',
        phone: '9414011223',
        source: 'WhatsApp',
        campaign_id: 'CMP007',
        status: 'contacted',
        created_date: '2026-06-12',
        revenue: 95000,
        notes: 'Requires site demonstration for 10 luxury suites.',
      },
    },
    {
      id: 8,
      title: 'Rohan Kapoor - Tech Park Vendor',
      subtitle: 'Pune • Google Ads • Revenue: ₹4,10,000',
      data: {
        name: 'Rohan Kapoor (Kapoor Solutions)',
        email: 'rohan@kapoorsolutions.com',
        phone: '9822099887',
        source: 'Google Ads',
        campaign_id: 'CMP008',
        status: 'converted',
        created_date: '2026-06-14',
        converted_date: '2026-06-18',
        revenue: 410000,
        notes: 'Payment received. Order dispatched via expedited freight.',
      },
    },
    {
      id: 9,
      title: 'Deepa Joshi - Boutique Chain Owner',
      subtitle: 'Kolkata • Facebook • Revenue: ₹1,60,000',
      data: {
        name: 'Deepa Joshi',
        email: 'deepa@silkandstyle.com',
        phone: '9830077665',
        source: 'Facebook',
        campaign_id: 'CMP009',
        status: 'contacted',
        created_date: '2026-06-15',
        revenue: 160000,
        notes: 'Follow up call scheduled for upcoming Tuesday.',
      },
    },
    {
      id: 10,
      title: 'Amit Singhal - Govt Supply Contractor',
      subtitle: 'Lucknow • LinkedIn • Revenue: ₹7,50,000',
      data: {
        name: 'Amit Singhal (Singhal Infra)',
        email: 'amit@singhalinfra.org',
        phone: '9415088990',
        source: 'Google Ads',
        campaign_id: 'CMP010',
        status: 'qualified',
        created_date: '2026-06-17',
        revenue: 750000,
        notes: 'Submitted tender documentation and sample units.',
      },
    },
  ],

  content: [
    {
      id: 1,
      title: 'Festival Season Promo Banner',
      subtitle: 'Instagram Photo • 18:00',
      data: {
        title: 'Festival Mega Discount Launch',
        platform: 'Instagram',
        content_type: 'image',
        scheduled_date: '2026-06-15',
        scheduled_time: '18:00',
        caption: 'Celebrate the festive season with up to 50% OFF! Limited time offer. Shop now link in bio! 🎉 #FestiveSale #Deals',
      },
    },
    {
      id: 2,
      title: 'CEO Industry Insights Post',
      subtitle: 'LinkedIn Text • 09:30',
      data: {
        title: 'Future of B2B Automation 2026',
        platform: 'LinkedIn',
        content_type: 'text',
        scheduled_date: '2026-06-16',
        scheduled_time: '09:30',
        caption: 'How AI and automated workflows are empowering modern SMBs across India to scale 10x faster without growing overheads.',
      },
    },
    {
      id: 3,
      title: 'VIP Discount Coupon Alert',
      subtitle: 'WhatsApp Photo • 11:00',
      data: {
        title: 'Exclusive VIP Weekend Pass',
        platform: 'WhatsApp',
        content_type: 'image',
        scheduled_date: '2026-06-17',
        scheduled_time: '11:00',
        caption: 'Special surprise for our VIP customers! Use coupon VIP50 at checkout to get ₹5,000 instant cashback today.',
      },
    },
    {
      id: 4,
      title: 'New Product Teaser Video Reel',
      subtitle: 'Instagram Photo • 19:30',
      data: {
        title: 'Unboxing Next-Gen Smart Hub',
        platform: 'Instagram',
        content_type: 'image',
        scheduled_date: '2026-06-18',
        scheduled_time: '19:30',
        caption: 'Something revolutionary is coming your way! Can you guess what it is? Drop your answers below! 💡🔥',
      },
    },
    {
      id: 5,
      title: 'Client Case Study Showcase',
      subtitle: 'Facebook Text • 14:00',
      data: {
        title: 'Tata Motors Success Story',
        platform: 'Facebook',
        content_type: 'text',
        scheduled_date: '2026-06-19',
        scheduled_time: '14:00',
        caption: 'Discover how Tata Motors saved ₹12 Lakhs annually by automating AMC contract renewals with Pucho Marketing OS.',
      },
    },
    {
      id: 6,
      title: 'Weekend Flash Deal Announcement',
      subtitle: 'Instagram Photo • 10:00',
      data: {
        title: '48-Hour Weekend Flash Sale',
        platform: 'Instagram',
        content_type: 'image',
        scheduled_date: '2026-06-20',
        scheduled_time: '10:00',
        caption: 'Tick Tock! ⏰ 48-Hour Flash Sale starts NOW! Grab your favorites before stocks run out.',
      },
    },
    {
      id: 7,
      title: 'Market Trends Report Summary',
      subtitle: 'LinkedIn Text • 08:30',
      data: {
        title: 'Q3 Retail Growth Trends India',
        platform: 'LinkedIn',
        content_type: 'text',
        scheduled_date: '2026-06-21',
        scheduled_time: '08:30',
        caption: 'Key key metrics every retail business owner must track in 2026 to maximize customer lifetime value.',
      },
    },
    {
      id: 8,
      title: 'Monsoon Care Tips & Hacks',
      subtitle: 'WhatsApp Photo • 12:00',
      data: {
        title: 'Essential Monsoon Equipment Care',
        platform: 'WhatsApp',
        content_type: 'image',
        scheduled_date: '2026-06-22',
        scheduled_time: '12:00',
        caption: 'Protect your appliances this rainy season with our top 5 maintenance tips from expert engineers.',
      },
    },
    {
      id: 9,
      title: 'Customer Review Highlight Reel',
      subtitle: 'Facebook Text • 16:00',
      data: {
        title: 'What Our Dealers Say About Us',
        platform: 'Facebook',
        content_type: 'text',
        scheduled_date: '2026-06-23',
        scheduled_time: '16:00',
        caption: '"Pucho Marketing OS made our field team 3x more efficient!" - Rajesh Traders, Delhi. Read full interview inside.',
      },
    },
    {
      id: 10,
      title: 'Behind-The-Scenes Factory Tour',
      subtitle: 'Instagram Photo • 17:00',
      data: {
        title: 'How Our Machines Are Crafted',
        platform: 'Instagram',
        content_type: 'image',
        scheduled_date: '2026-06-24',
        scheduled_time: '17:00',
        caption: 'Take a quick peek inside our state-of-the-art manufacturing plant in Pune! Precision engineering at work ⚙️✨',
      },
    },
  ],

  broadcast: [
    {
      id: 1,
      title: 'Summer Sale WhatsApp Blast',
      subtitle: 'WhatsApp • Segment: All Customers',
      data: {
        channel: 'whatsapp',
        segment: 'all',
        message: 'Hello {name}! Enjoy up to 30% OFF on all purchases this week. Click here to claim: https://pucho.ai/deal',
        scheduled_date: '2026-06-20',
        scheduled_time: '10:00',
      },
    },
    {
      id: 2,
      title: 'New Product Catalog Email Broadcast',
      subtitle: 'Email • Segment: VIP Clients',
      data: {
        channel: 'email',
        segment: 'vip',
        message: 'Dear {name}, We are thrilled to introduce our 2026 Product Catalog with exclusive B2B pricing for VIP partners.',
        scheduled_date: '2026-06-21',
        scheduled_time: '11:30',
      },
    },
    {
      id: 3,
      title: 'Inactive Leads Winback Campaign',
      subtitle: 'WhatsApp • Segment: Inactive Leads',
      data: {
        channel: 'whatsapp',
        segment: 'inactive_users',
        message: 'We miss you, {name}! Here is a special ₹1,000 discount voucher on your next booking: COMEBACK1000.',
        scheduled_date: '2026-06-22',
        scheduled_time: '14:00',
      },
    },
    {
      id: 4,
      title: 'Payment Reminder & Renewal Alert',
      subtitle: 'WhatsApp • Segment: Due AMC Accounts',
      data: {
        channel: 'whatsapp',
        segment: 'all',
        message: 'Hi {name}, your annual AMC agreement is due for renewal next week. Renew now to avoid service gap.',
        scheduled_date: '2026-06-23',
        scheduled_time: '09:00',
      },
    },
    {
      id: 5,
      title: 'Exclusive B2B Webinar Invitation',
      subtitle: 'Email • Segment: New Leads',
      data: {
        channel: 'email',
        segment: 'new_leads',
        message: 'Join our exclusive webinar: "Maximizing ROI with Marketing Automation" this Thursday at 4 PM IST.',
        scheduled_date: '2026-06-24',
        scheduled_time: '16:00',
      },
    },
    {
      id: 6,
      title: 'Monsoon Clearance Coupon Blast',
      subtitle: 'WhatsApp • Segment: Retail Buyers',
      data: {
        channel: 'whatsapp',
        segment: 'all',
        message: 'Monsoon Mega Outlet Fest is live! Get instant free delivery on all orders placed today.',
        scheduled_date: '2026-06-25',
        scheduled_time: '12:00',
      },
    },
    {
      id: 7,
      title: 'Monthly Industry Roundup Newsletter',
      subtitle: 'Email • Segment: All Subscribers',
      data: {
        channel: 'email',
        segment: 'all',
        message: 'Check out the June Edition of Pucho Insights: Top 10 trends shaping Indian retail & manufacturing.',
        scheduled_date: '2026-06-26',
        scheduled_time: '08:30',
      },
    },
    {
      id: 8,
      title: 'Festive Early Access Voucher',
      subtitle: 'WhatsApp • Segment: Active Shoppers',
      data: {
        channel: 'whatsapp',
        segment: 'vip',
        message: 'Hey {name}, enjoy early access to our Diwali pre-booking sale 24 hours before the general public!',
        scheduled_date: '2026-06-27',
        scheduled_time: '15:00',
      },
    },
    {
      id: 9,
      title: 'Product Maintenance Guide PDF',
      subtitle: 'Email • Segment: Existing Buyers',
      data: {
        channel: 'email',
        segment: 'all',
        message: 'Download your free 2026 Equipment Maintenance Checklist & Service Guidelines from Pucho Support.',
        scheduled_date: '2026-06-28',
        scheduled_time: '10:30',
      },
    },
    {
      id: 10,
      title: 'Quarter-End Stock Rebate Offer',
      subtitle: 'WhatsApp • Segment: Dealers & Distributors',
      data: {
        channel: 'whatsapp',
        segment: 'all',
        message: 'Special Q2 Closing Rebate! Extra 5% credit on orders above ₹1,00,000 booked before month end.',
        scheduled_date: '2026-06-29',
        scheduled_time: '17:00',
      },
    },
  ],

  testimonials: [
    {
      id: 1,
      title: 'Aditya Verma (Tata Motors)',
      subtitle: '5 Stars • "Outstanding service and rapid response time!"',
      data: {
        customer: 'Aditya Verma (Tata Motors)',
        email: 'aditya.verma@tatamotors.com',
        rating: 5,
        review: 'Pucho Marketing OS transformed our leads tracking and contract renewal speed completely. 10/10 service!',
        status: 'Collected',
      },
    },
    {
      id: 2,
      title: 'Swati Kulkarni (Reliance Digital)',
      subtitle: '5 Stars • "Increased our conversion by 40%!"',
      data: {
        customer: 'Swati Kulkarni (Reliance Digital)',
        email: 'swati.k@reliancedigital.in',
        rating: 5,
        review: 'Automated WhatsApp broadcasts doubled our customer engagement rate during the festive sale.',
        status: 'Collected',
      },
    },
    {
      id: 3,
      title: 'Rakesh Jhunjhunwala Traders',
      subtitle: '4 Stars • "Very smooth automation flow"',
      data: {
        customer: 'Rakesh Jhunjhunwala Traders',
        email: 'rakesh@rjtraders.com',
        rating: 4,
        review: 'Great dashboard layout and very fast quotation PDF generation for our field sales team.',
        status: 'Collected',
      },
    },
    {
      id: 4,
      title: 'Dr. Neha Saxena (Apex Hospitals)',
      subtitle: '5 Stars • "Highly reliable AMC tracking"',
      data: {
        customer: 'Dr. Neha Saxena (Apex Hospitals)',
        email: 'neha.saxena@apexhospitals.com',
        rating: 5,
        review: 'We no longer miss equipment maintenance deadlines thanks to automated renewal reminders.',
        status: 'Collected',
      },
    },
    {
      id: 5,
      title: 'Kavita Nair (Nair Fashion House)',
      subtitle: '5 Stars • "The review generator is amazing"',
      data: {
        customer: 'Kavita Nair (Nair Fashion House)',
        email: 'kavita@nairfashion.com',
        rating: 5,
        review: 'Collecting social proof reviews from our customers has never been so seamless and automated!',
        status: 'Collected',
      },
    },
    {
      id: 6,
      title: 'Harsh Vardhan (Vardhan Logistics)',
      subtitle: '4 Stars • "10x faster dealer payouts"',
      data: {
        customer: 'Harsh Vardhan (Vardhan Logistics)',
        email: 'harsh@vardhanlogistics.in',
        rating: 4,
        review: 'Dealer scheme claim verification process is now transparent and lightning quick.',
        status: 'Collected',
      },
    },
    {
      id: 7,
      title: 'Sanjay Mehta (Mehta Enterprises)',
      subtitle: '5 Stars • "Best KYC onboarding portal"',
      data: {
        customer: 'Sanjay Mehta (Mehta Enterprises)',
        email: 'sanjay@mehtaenterprises.co.in',
        rating: 5,
        review: 'Onboarding new regional dealers takes minutes instead of days. Super easy documentation link.',
        status: 'Collected',
      },
    },
    {
      id: 8,
      title: 'Pooja Deshmukh (Deshmukh Designs)',
      subtitle: '5 Stars • "Clean interface and quick test data"',
      data: {
        customer: 'Pooja Deshmukh (Deshmukh Designs)',
        email: 'pooja@deshmukhdesigns.com',
        rating: 5,
        review: 'The design aesthetic is super premium and the 1-click test fill features save hours of testing time.',
        status: 'Collected',
      },
    },
    {
      id: 9,
      title: 'Manoj Bajpayee (Star Retail)',
      subtitle: '4 Stars • "Solid support and webhooks"',
      data: {
        customer: 'Manoj Bajpayee (Star Retail)',
        email: 'manoj@starretail.org',
        rating: 4,
        review: 'Seamless webhook integration with our backend ERP system. Very happy with the performance.',
        status: 'Collected',
      },
    },
    {
      id: 10,
      title: 'Tarun Gill (Fitness First)',
      subtitle: '5 Stars • "Outstanding overall platform"',
      data: {
        customer: 'Tarun Gill (Fitness First Gyms)',
        email: 'tarun@fitnessfirst.in',
        rating: 5,
        review: 'Highly recommended for any Indian business looking to scale sales & marketing operations!',
        status: 'Collected',
      },
    },
  ],

  amc: [
    {
      id: 1,
      title: 'Tata Motors - Industrial AC Unit',
      subtitle: 'Value: ₹65,000 • Active • Expiry: 2026-08-15',
      data: {
        customer: 'Tata Motors Manufacturing',
        asset: 'Industrial Chiller & AC Unit 50HP',
        endDate: '2026-08-15',
        value: 65000,
        status: 'Active',
      },
    },
    {
      id: 2,
      title: 'Reliance Jio - Enterprise Server Rack',
      subtitle: 'Value: ₹1,50,000 • Active • Expiry: 2026-12-30',
      data: {
        customer: 'Reliance Jio Infocomm',
        asset: 'Data Center Cooling & Rack Maintenance',
        endDate: '2026-12-30',
        value: 150000,
        status: 'Active',
      },
    },
    {
      id: 3,
      title: 'Infosys Ltd - Modular UPS Backup',
      subtitle: 'Value: ₹28,000 • Expiring • Expiry: 2026-06-25',
      data: {
        customer: 'Infosys Software Campus',
        asset: 'Modular 100kVA UPS Battery Backup',
        endDate: '2026-06-25',
        value: 28000,
        status: 'Expiring',
      },
    },
    {
      id: 4,
      title: 'Wipro - Power Generator 250kVA',
      subtitle: 'Value: ₹95,000 • Active • Expiry: 2026-10-10',
      data: {
        customer: 'Wipro Technologies',
        asset: 'Cummins Diesel Generator 250kVA',
        endDate: '2026-10-10',
        value: 95000,
        status: 'Active',
      },
    },
    {
      id: 5,
      title: 'Maruti Suzuki - Robotic Arm Unit',
      subtitle: 'Value: ₹2,80,000 • Active • Expiry: 2027-01-15',
      data: {
        customer: 'Maruti Suzuki India',
        asset: 'KUKA Robotic Welding Arm #4',
        endDate: '2027-01-15',
        value: 280000,
        status: 'Active',
      },
    },
    {
      id: 6,
      title: 'Adani Power - Substation Transformer',
      subtitle: 'Value: ₹2,10,000 • Expiring • Expiry: 2026-06-18',
      data: {
        customer: 'Adani Power Plant',
        asset: 'High Voltage Substation Transformer',
        endDate: '2026-06-18',
        value: 210000,
        status: 'Expiring',
      },
    },
    {
      id: 7,
      title: 'HCL Tech - HVAC Chiller Plant',
      subtitle: 'Value: ₹1,75,000 • Active • Expiry: 2026-11-20',
      data: {
        customer: 'HCL Technologies Campus',
        asset: 'Centralized HVAC Chiller Plant',
        endDate: '2026-11-20',
        value: 175000,
        status: 'Active',
      },
    },
    {
      id: 8,
      title: 'Godrej Appliances - Compressors',
      subtitle: 'Value: ₹85,000 • Active • Expiry: 2026-09-05',
      data: {
        customer: 'Godrej & Boyce Mfg',
        asset: 'Industrial Cold Storage Compressors',
        endDate: '2026-09-05',
        value: 85000,
        status: 'Active',
      },
    },
    {
      id: 9,
      title: 'Hero MotoCorp - Conveyor System',
      subtitle: 'Value: ₹3,40,000 • Expiring • Expiry: 2026-06-30',
      data: {
        customer: 'Hero MotoCorp Plant',
        asset: 'Automated Assembly Line Conveyor',
        endDate: '2026-06-30',
        value: 340000,
        status: 'Expiring',
      },
    },
    {
      id: 10,
      title: 'L&T Heavy Engineering - Hydraulics',
      subtitle: 'Value: ₹4,50,000 • Active • Expiry: 2027-03-31',
      data: {
        customer: 'Larsen & Toubro Division',
        asset: 'Heavy Duty Crane Hydraulics Service',
        endDate: '2027-03-31',
        value: 450000,
        status: 'Active',
      },
    },
  ],

  dealerSchemes: [
    {
      id: 1,
      title: 'Monsoon Special Distributor Scheme',
      subtitle: 'Inverter AC 1.5 Ton • 15% Cashback',
      data: {
        scheme_name: 'Monsoon Special Distributor Discount',
        product: 'Inverter AC 1.5 Ton',
        discount: '15% Cashback + Free Shipping',
        valid_till: '2026-08-31',
      },
    },
    {
      id: 2,
      title: 'Festive Advance Order Bonus',
      subtitle: 'Smart Ultra HD TVs • 20% Instant Discount',
      data: {
        scheme_name: 'Festive Pre-Booking Bonanza',
        product: 'Smart Ultra HD TVs 55"',
        discount: '20% Instant Trade Discount',
        valid_till: '2026-10-31',
      },
    },
    {
      id: 3,
      title: 'Early Bird Q3 Target Achievement',
      subtitle: 'Double Door Refrigerators • Dubai Trip Voucher',
      data: {
        scheme_name: 'Q3 Star Performer Reward Scheme',
        product: 'Double Door Frost Free Refrigerators',
        discount: 'Trip to Dubai for 2 (On 100 Units)',
        valid_till: '2026-09-30',
      },
    },
    {
      id: 4,
      title: 'Bulk Purchase Volume Rebate',
      subtitle: 'Front Load Washing Machines • ₹50,000 Credit',
      data: {
        scheme_name: 'Volume Super Rebate 2026',
        product: 'Front Load Washing Machines 8kg',
        discount: '₹50,000 Direct Cash Credit',
        valid_till: '2026-07-31',
      },
    },
    {
      id: 5,
      title: 'New Dealer Welcome Discount',
      subtitle: 'Solo & Convection Microwaves • 10% Extra Margin',
      data: {
        scheme_name: 'New Dealer Onboarding Special',
        product: 'Convection Microwave Ovens 28L',
        discount: '10% Extra Retail Margin',
        valid_till: '2026-12-31',
      },
    },
    {
      id: 6,
      title: 'Tier-2 Market Penetration Scheme',
      subtitle: 'Hybrid Solar Inverters • 18% Subsidy Pass',
      data: {
        scheme_name: 'Solar Green India Drive',
        product: 'Hybrid Solar Inverters 5kW',
        discount: '18% Special Government Subsidy Pass',
        valid_till: '2026-11-15',
      },
    },
    {
      id: 7,
      title: 'Year-End Clearance Booster',
      subtitle: 'Enterprise Laptops • Buy 10 Get 1 Free',
      data: {
        scheme_name: 'Year End Clearance Incentive',
        product: 'Enterprise Core i7 Laptops',
        discount: 'Buy 10 Units Get 1 Unit FREE',
        valid_till: '2026-12-31',
      },
    },
    {
      id: 8,
      title: 'Gold Tier Loyalty Bonus',
      subtitle: 'Premium Home Appliances • Gold Coin Voucher',
      data: {
        scheme_name: 'Gold Club Dealer Appreciation',
        product: 'All Premium Kitchen Appliances',
        discount: '10 Gram 24K Gold Coin Voucher',
        valid_till: '2026-11-30',
      },
    },
    {
      id: 9,
      title: 'Retailer Flash Weekend Incentive',
      subtitle: 'RO Water Purifiers • ₹2,000 Cash/unit',
      data: {
        scheme_name: 'Weekend Retail Blitz Scheme',
        product: '7-Stage RO Water Purifiers',
        discount: '₹2,000 Instant Cash per unit sold',
        valid_till: '2026-06-30',
      },
    },
    {
      id: 10,
      title: 'Pre-Diwali Stocking Bonanza',
      subtitle: 'Wireless Audio Soundbars • 25% Trade Off',
      data: {
        scheme_name: 'Diwali Stocking Bonanza 2026',
        product: 'Dolby Atmos Soundbars 300W',
        discount: '25% Trade Discount + Extended Warranty',
        valid_till: '2026-10-15',
      },
    },
  ],

  fieldSales: [
    {
      id: 1,
      title: 'Amit Kumar @ Sharma Kirana Store',
      subtitle: 'Delhi • Status: Completed • Order: ₹45,000',
      data: {
        rep: 'Amit Kumar',
        customer: 'Sharma Kirana Store',
        status: 'Completed',
        orders: '₹45,000',
        location: 'Delhi (28.6139, 77.2090)',
        remarks: 'Delivered initial stock and collected cheque for previous bill.',
      },
    },
    {
      id: 2,
      title: 'Sumit Singh @ Verma Departmental',
      subtitle: 'Noida • Status: Completed • Stock Check',
      data: {
        rep: 'Sumit Singh',
        customer: 'Verma Departmental Store',
        status: 'Completed',
        orders: 'None (Stock Audit)',
        location: 'Noida (28.5355, 77.3910)',
        remarks: 'Inventory audit completed. Shelf display updated with new branding.',
      },
    },
    {
      id: 3,
      title: 'Rahul Dev @ Gupta Mega Mart',
      subtitle: 'Gurugram • Status: Scheduled • Order: Pending',
      data: {
        rep: 'Rahul Dev',
        customer: 'Gupta Mega Mart',
        status: 'Scheduled',
        orders: 'Pending Order',
        location: 'Gurugram (28.4595, 77.0266)',
        remarks: 'Monthly contract review meeting scheduled with store manager.',
      },
    },
    {
      id: 4,
      title: 'Priya Sharma @ Chawla Electronics',
      subtitle: 'Faridabad • Status: Completed • Order: ₹25,000',
      data: {
        rep: 'Priya Sharma',
        customer: 'Chawla Electronics',
        status: 'Completed',
        orders: '₹25,000',
        location: 'Faridabad (28.4089, 77.3178)',
        remarks: 'Booked 5 units of Smart ACs for upcoming sale.',
      },
    },
    {
      id: 5,
      title: 'Amit Kumar @ Ahuja General Store',
      subtitle: 'Delhi • Status: Completed • Order: ₹12,000',
      data: {
        rep: 'Amit Kumar',
        customer: 'Ahuja General Store',
        status: 'Completed',
        orders: '₹12,000',
        location: 'Delhi (28.6562, 77.2410)',
        remarks: 'Replaced damaged display unit and taken restock order.',
      },
    },
    {
      id: 6,
      title: 'Sumit Singh @ Apex Hypermarket',
      subtitle: 'Ghaziabad • Status: Completed • Order: ₹48,000',
      data: {
        rep: 'Sumit Singh',
        customer: 'Apex Hypermarket',
        status: 'Completed',
        orders: '₹48,000',
        location: 'Ghaziabad (28.6692, 77.4538)',
        remarks: 'Negotiated end-cap display placement for festival season.',
      },
    },
    {
      id: 7,
      title: 'Rahul Dev @ National Provision Store',
      subtitle: 'Greater Noida • Status: Completed • Order: ₹1,50,000',
      data: {
        rep: 'Rahul Dev',
        customer: 'National Provision Store',
        status: 'Completed',
        orders: '₹1,50,000',
        location: 'Greater Noida (28.4744, 77.5040)',
        remarks: 'Major wholesale booking confirmed. Dispatch requested by Friday.',
      },
    },
    {
      id: 8,
      title: 'Priya Sharma @ Metropolitan Mart',
      subtitle: 'Delhi • Status: Scheduled • Product Demo',
      data: {
        rep: 'Priya Sharma',
        customer: 'Metropolitan Mart',
        status: 'Scheduled',
        orders: 'Demo Scheduled',
        location: 'Delhi (28.6139, 77.2090)',
        remarks: 'Live demonstration of new solar inverter line.',
      },
    },
    {
      id: 9,
      title: 'Amit Kumar @ Singla Hardware',
      subtitle: 'Sonipat • Status: Completed • Order: ₹32,000',
      data: {
        rep: 'Amit Kumar',
        customer: 'Singla Hardware & Electricals',
        status: 'Completed',
        orders: '₹32,000',
        location: 'Sonipat (28.9931, 77.0151)',
        remarks: 'Collected payment cheque and logged warranty registration.',
      },
    },
    {
      id: 10,
      title: 'Sumit Singh @ Vanguard Supermarket',
      subtitle: 'Noida • Status: Completed • Order: ₹64,000',
      data: {
        rep: 'Sumit Singh',
        customer: 'Vanguard Supermarket',
        status: 'Completed',
        orders: '₹64,000',
        location: 'Noida (28.5355, 77.3910)',
        remarks: 'Store manager extended order volume by 20%.',
      },
    },
  ],

  quotations: [
    {
      id: 1,
      title: 'Reliance Retail - POS Terminals',
      subtitle: '25 Units @ ₹18,500/unit (Total: ₹4,62,500)',
      data: {
        customer: 'Reliance Retail Pvt Ltd',
        email: 'procurement@relianceretail.com',
        phone: '9820099112',
        product: 'Touchscreen POS Billing Terminals',
        quantity: 25,
        unit_price: 18500,
        logo_url: 'https://raw.githubusercontent.com/damini07le-byte/pucho-assets/main/logo.png',
      },
    },
    {
      id: 2,
      title: 'Tata Consumer - Packaging Boxes',
      subtitle: '5000 Units @ ₹35/unit (Total: ₹1,75,000)',
      data: {
        customer: 'Tata Consumer Products Ltd',
        email: 'purchasing@tataconsumer.com',
        phone: '9819022334',
        product: 'Heavy Duty Corrugated Shipping Boxes',
        quantity: 5000,
        unit_price: 35,
        logo_url: 'https://raw.githubusercontent.com/damini07le-byte/pucho-assets/main/logo.png',
      },
    },
    {
      id: 3,
      title: 'Mahindra & Mahindra - Hydraulic Valves',
      subtitle: '50 Units @ ₹12,000/unit (Total: ₹6,00,000)',
      data: {
        customer: 'Mahindra & Mahindra Automotive',
        email: 'vendor.connect@mahindra.com',
        phone: '9822044556',
        product: 'Precision Electro-Hydraulic Valves',
        quantity: 50,
        unit_price: 12000,
        logo_url: 'https://raw.githubusercontent.com/damini07le-byte/pucho-assets/main/logo.png',
      },
    },
    {
      id: 4,
      title: 'Sun Pharma - Cleanroom Air Filters',
      subtitle: '100 Units @ ₹4,500/unit (Total: ₹4,50,000)',
      data: {
        customer: 'Sun Pharmaceutical Industries',
        email: 'facilities@sunpharma.com',
        phone: '9833077889',
        product: 'HEPA High-Efficiency Air Filters',
        quantity: 100,
        unit_price: 4500,
        logo_url: 'https://raw.githubusercontent.com/damini07le-byte/pucho-assets/main/logo.png',
      },
    },
    {
      id: 5,
      title: 'Tech Mahindra - Employee Kits',
      subtitle: '500 Units @ ₹1,200/unit (Total: ₹6,00,000)',
      data: {
        customer: 'Tech Mahindra Corporate HQ',
        email: 'admin.purchases@techmahindra.com',
        phone: '9840011223',
        product: 'Customized Welcome Tech Gift Box',
        quantity: 500,
        unit_price: 1200,
        logo_url: 'https://raw.githubusercontent.com/damini07le-byte/pucho-assets/main/logo.png',
      },
    },
    {
      id: 6,
      title: 'DLF Commercial - Access Security Gates',
      subtitle: '8 Units @ ₹1,45,000/unit (Total: ₹11,60,000)',
      data: {
        customer: 'DLF Commercial Properties',
        email: 'estate.security@dlf.in',
        phone: '9811055667',
        product: 'Automated Flap Barrier Turnstiles',
        quantity: 8,
        unit_price: 145000,
        logo_url: 'https://raw.githubusercontent.com/damini07le-byte/pucho-assets/main/logo.png',
      },
    },
    {
      id: 7,
      title: 'Asian Paints - Pigment Mixers',
      subtitle: '4 Units @ ₹2,80,000/unit (Total: ₹11,20,000)',
      data: {
        customer: 'Asian Paints Manufacturing Division',
        email: 'plant.procurement@asianpaints.com',
        phone: '9820033445',
        product: 'High Shear Industrial Chemical Mixers',
        quantity: 4,
        unit_price: 280000,
        logo_url: 'https://raw.githubusercontent.com/damini07le-byte/pucho-assets/main/logo.png',
      },
    },
    {
      id: 8,
      title: 'Flipkart Logistics - Barcode Scanners',
      subtitle: '30 Units @ ₹15,000/unit (Total: ₹4,50,000)',
      data: {
        customer: 'Flipkart Logistics Hub',
        email: 'hub.ops@flipkart.com',
        phone: '9880066778',
        product: 'Long Range Wireless 2D Barcode Scanners',
        quantity: 30,
        unit_price: 15000,
        logo_url: 'https://raw.githubusercontent.com/damini07le-byte/pucho-assets/main/logo.png',
      },
    },
    {
      id: 9,
      title: 'Apollo Hospitals - Patient Monitors',
      subtitle: '15 Units @ ₹42,000/unit (Total: ₹6,30,000)',
      data: {
        customer: 'Apollo Hospitals Group',
        email: 'biomedical@apollohospitals.com',
        phone: '9841022334',
        product: 'Multi-Parameter ICU Patient Monitors',
        quantity: 15,
        unit_price: 42000,
        logo_url: 'https://raw.githubusercontent.com/damini07le-byte/pucho-assets/main/logo.png',
      },
    },
    {
      id: 10,
      title: 'Zomato Fleet - Electric Delivery Scooters',
      subtitle: '10 Units @ ₹75,000/unit (Total: ₹7,50,000)',
      data: {
        customer: 'Zomato Green Delivery Fleet',
        email: 'fleet.ops@zomato.com',
        phone: '9810088990',
        product: 'High-Range EV Cargo Delivery Scooters',
        quantity: 10,
        unit_price: 75000,
        logo_url: 'https://raw.githubusercontent.com/damini07le-byte/pucho-assets/main/logo.png',
      },
    },
  ],

  onboarding: [
    {
      id: 1,
      title: 'Royal Trade Pvt Ltd (Delhi)',
      subtitle: 'GST: 07AAACR1234F1Z5 • Required Docs: GST, PAN',
      data: {
        name: 'Royal Trade Pvt Ltd',
        phone: '9811099887',
        email: 'kyc@royaltrade.co.in',
        documents: ['GST Certificate', 'PAN Card', 'Cancelled Cheque'],
      },
    },
    {
      id: 2,
      title: 'Apex Electronics LLP (Bangalore)',
      subtitle: 'GST: 29AABCA9876E1Z2 • Required Docs: GST, Bank Proof',
      data: {
        name: 'Apex Electronics LLP',
        phone: '9900011223',
        email: 'onboarding@apexelectronics.in',
        documents: ['GST Certificate', 'PAN Card', 'Bank Passbook Proof'],
      },
    },
    {
      id: 3,
      title: 'Trident Global Corp (Mumbai)',
      subtitle: 'GST: 27AABCT5544K1Z9 • Required Docs: GST, IEC License',
      data: {
        name: 'Trident Global Corp',
        phone: '9820033445',
        email: 'compliance@tridentglobal.com',
        documents: ['GST Certificate', 'PAN Card', 'Import-Export License'],
      },
    },
    {
      id: 4,
      title: 'Zenith Hardware & Tools (Hyderabad)',
      subtitle: 'GST: 36AABCZ4433J1Z8 • Required Docs: GST, Shop Act',
      data: {
        name: 'Zenith Hardware & Tools',
        phone: '9700055667',
        email: 'info@zenithhardware.in',
        documents: ['GST Certificate', 'PAN Card', 'Shop Establishment Act'],
      },
    },
    {
      id: 5,
      title: 'Supreme Agencies (Chennai)',
      subtitle: 'GST: 33AABCS1122H1Z4 • Required Docs: GST, FSSAI',
      data: {
        name: 'Supreme Wholesale Agencies',
        phone: '9444077889',
        email: 'admin@supremeagencies.com',
        documents: ['GST Certificate', 'PAN Card', 'FSSAI License'],
      },
    },
    {
      id: 6,
      title: 'Metro Builders Mart (Pune)',
      subtitle: 'GST: 27AABCM6677L1Z3 • Required Docs: GST, Partnership Deed',
      data: {
        name: 'Metro Builders Mart',
        phone: '9822088990',
        email: 'partners@metromart.in',
        documents: ['GST Certificate', 'PAN Card', 'Partnership Deed'],
      },
    },
    {
      id: 7,
      title: 'Bharat Commercial Traders (Ahmedabad)',
      subtitle: 'GST: 24AABCB3322M1Z1 • Required Docs: GST, MSME Cert',
      data: {
        name: 'Bharat Commercial Traders',
        phone: '9898022334',
        email: 'accounts@bharattraders.com',
        documents: ['GST Certificate', 'PAN Card', 'Udyam MSME Certificate'],
      },
    },
    {
      id: 8,
      title: 'Horizon Tech Solutions (Kolkata)',
      subtitle: 'GST: 19AABCH9988N1Z0 • Required Docs: GST, ISO Cert',
      data: {
        name: 'Horizon Tech Solutions',
        phone: '9830044556',
        email: 'kyc@horizontech.co.in',
        documents: ['GST Certificate', 'PAN Card', 'ISO 9001 Certificate'],
      },
    },
    {
      id: 9,
      title: 'City Electricals & Spares (Jaipur)',
      subtitle: 'GST: 08AABCC4411P1Z7 • Required Docs: GST, Trade License',
      data: {
        name: 'City Electricals & Spares',
        phone: '9414066778',
        email: 'cityelectricals@gmail.com',
        documents: ['GST Certificate', 'PAN Card', 'Municipal Trade License'],
      },
    },
    {
      id: 10,
      title: 'Fortune India Logistics (Chandigarh)',
      subtitle: 'GST: 04AABCF2211Q1Z6 • Required Docs: GST, Transport License',
      data: {
        name: 'Fortune India Logistics',
        phone: '9815088990',
        email: 'ops@fortunelogistics.in',
        documents: ['GST Certificate', 'PAN Card', 'Commercial Vehicle Permit'],
      },
    },
    ],
}
